TABLE_NAME2ID: dict[str, int] = {
    "customer": 0,
    "lineitem": 1,
    "nation": 2,
    "orders": 3,
    "part": 4,
    "partsupp": 5,
    "region": 6,
    "supplier": 7,
}

TABLE_KEY2ID: dict[str, int] = {
    "c_custkey": 0,
    "c_name": 1,
    "c_address": 2,
    "c_nationkey": 3,
    "c_phone": 4,
    "c_acctbal": 5,
    "c_mktsegment": 6,
    "c_comment": 7,
    "l_orderkey": 8,
    "l_partkey": 9,
    "l_suppkey": 10,
    "l_linenumber": 11,
    "l_quantity": 12,
    "l_extendedprice": 13,
    "l_discount": 14,
    "l_tax": 15,
    "l_returnflag": 16,
    "l_linestatus": 17,
    "l_shipdate": 18,
    "l_commitdate": 19,
    "l_receiptdate": 20,
    "l_shipinstruct": 21,
    "l_shipmode": 22,
    "l_comment": 23,
    "n_nationkey": 24,
    "n_name": 25,
    "n_regionkey": 26,
    "n_comment": 27,
    "o_orderkey": 28,
    "o_custkey": 29,
    "o_orderstatus": 30,
    "o_totalprice": 31,
    "o_orderdate": 32,
    "o_orderpriority": 33,
    "o_clerk": 34,
    "o_shippriority": 35,
    "o_comment": 36,
    "p_partkey": 37,
    "p_name": 38,
    "p_mfgr": 39,
    "p_brand": 40,
    "p_type": 41,
    "p_size": 42,
    "p_container": 43,
    "p_retailprice": 44,
    "p_comment": 45,
    "ps_partkey": 46,
    "ps_suppkey": 47,
    "ps_availqty": 48,
    "ps_supplycost": 49,
    "ps_comment": 50,
    "r_regionkey": 51,
    "r_name": 52,
    "r_comment": 53,
    "s_suppkey": 54,
    "s_name": 55,
    "s_address": 56,
    "s_nationkey": 57,
    "s_phone": 58,
    "s_acctbal": 59,
    "s_comment": 60,
}

OP_NAME2ID: dict[str, int] = {
    "EQ": 0,
    "LT": 1,
    "GT": 2,
    "LTE": 3,
    "GTE": 4,
    "NEQ": 5,
}
